### PR TITLE
Flight queries and pages

### PR DESCRIPTION
**Pull request by kevinxchan**
This PR is mostly just to keep you guys updated, I don't think it's ready to be merged quite yet. I've implemented most of the queries on the doc, and made some pages to display results too. The formatting/styling isn't the best since I was looking to get it working first, and I think I can touch it up /make it look nicer once everything works properly. 

Just a couple things to note:
1. The Search feature is currently in the NavBar, and that can be changed once the login pages are implemented and this can be re-routed. 
2. On the booking page, I currently have it so the user must put in their email. I think this can be changed once the login is implemented so users can't just put in an arbitrary email when reserving their seat.
3. Also on the booking page, the user has to input a reservation ID...it's kind of strange, but I'm just going based off the doc (query 6).
4. The last part of the gif where the booking is created doesn't properly display the success message after clicking, not sure why. But it works because if you check on pgAdmin4, you'll see a new row in `Reserves_Occupies_Reservation` and `reserved` changed from 0 to 1 in `Has_Seats_4` for the seat booked.
5. Under the "additional search" page, I'll add queries 4 and 5, and then that should cover all the queries regarding flights/bookings in the doc.

http://g.recordit.co/2z11dMHU47.gif

EDIT:

Finished working on the additional queries page (point #5 above), here's another GIF for you guys to see the functionality. This page is mostly just to satisfy what's on our doc. I think it's ready to be merged now.

http://g.recordit.co/NS7oSZbvqk.gif

### CODE REVIEW

**Comment by bchen229** [comment]
For reservation id, maybe we can generate an id from the code (like a guid or something)

**Comment by kevinxchan** [comment]
Yeah I agree. Or something like `SERIAL` that was in the `Users` table from the project starter

**Comment by AaronCui** [comment]
Yes reservation id should be generated not an input by user. We can simply have generate it 1 by 1 in series like sample project starter. A better choice would be to use a UUID generator something like https://github.com/broofa/node-uuid but we can also write a simple one ourselves leveraging known info. May not fit in char length 20 however. 

I can add it as it's non-core, don't split your focus. Put in any placeholder that works for now.

**Comment by AaronCui** [comment]
Overall looks good. Thanks for the great work! Especially the gif recording saves me the time in trying to run your code on my local 👍 

One nitpick - I understand it's still in dev, but I'd recommend start squashing commits. It's a bit hard for people to find meaningful diff. Try to rebase instead of merge in future as well (I forgot about this too using github UI, all our PR should be rebased rather than having a merge commit, it's pointless for now). We shouldn't use squash and merge because one PR may have multiple meaningful commits, the commiter should manage that. 

Maybe you know maybe you don't, a simple way to reset everything is as follows: 
1. be on ur dev branch 
2. `git stash` all uncommitted changes 
3. `git log` to see history (most importantly find the one before ur changes (origin/master, origin/HEAD ...) 
4. do `git reset --soft <<commit SHA1 id>>`  or `git reset --soft HEAD~2` (where number is how many commits back, I recommend not doing this cuz sometime 1 over can be painful, use commit id instead) 

This will set state back to the commit before u did any change, but "soft" means it didn't remove any of ur new changes. They should persist and thus becomes uncommitted changes. Now you can add a selection of files at a time, do 1 commit, then another selection, another commit, thus no file will be changed in more than 1 commit. In this case all your changes can be in 1 commit, so add all and commit once is fine. 

5. `git stash pop` if you had uncommitted changes before doing the squash. 

I know we are both just starting and also in our last stretch lol, but I think these are not too much effort and make our repo very clean and professional :) 

PS: Treat main branch as holy but don't mind rewriting your own branch. After resetting your commits you'll have to do a force push instead `git push -f origin <<branch>>` since the history won't agree. 

PPS: May be headache if the merge in the middle of progress had conflicts. This is why rebase is better than merge. All your commits is moved to AFTER the newest merge (eg from main branch). Thus your progress won't be split up by a merge when it does not make conceptual sense. I digress, if this actually causes issue, don't bother with it.

**Review by AaronCui — APPROVED** [review]
Overall looks good with some areas needing improvement / continued development. Merging first without detailed comments as baseline, will add more in future PRs / issues.

**Pull request merged**
