### PR TITLE
Insert queries

### PR DESCRIPTION
**Pull request by bchen229**
Update Airplane_4 FK
Add new YVR to SFO and SFO to YVR flights for plane 1234 and airline AC for different flights
Add seats for every seat_no for every flight

### CODE REVIEW

**Comment by AaronCui** [comment]
Some of these are non-trivial changes to the table. Is it the things we discussed during Thursday or has there been more changes? I've put my questions in review. 

I know you've been updating our formal spec doc but no one's reading it at this point. Please be more descriptive in PR description so others know what's going on. I will also upload the formal spec doc into the repo instead so we can see diff in the future. But plz reply here or msg me for this.

**Review by AaronCui — CHANGES_REQUESTED** [review]
I don't understand why airplane is now using full flight info as primary key. We have LandsAt_TakesOff_Flight for that. This is suppose to be a physical plane, it's not a flight. Maybe you are trying to fix some queries or class req but this doesn't make sense conceptually. 

Doesn't mean I'm requesting change, but please explain sufficiently in comment or message me directly.

**Comment by bchen229** [comment]
If plane id is the PK then one plane can only be related to one flight ever. If we have flight as PK then the one plane can be used in many flights.

**Comment by kevinxchan** [comment]
Yeah so specifically, check out `Airplane_4`. The primary key `plane_id` determines the `flight_no`, `airline`, `date` and `model`. So right now as is, a single physical plane (which `plane_id` represents) can only be used in a single logistical flight. So we can't have flight no. `099` being used across two flights on different days for example; `Airplane_4` won't allow that. 

And just a note I actually read the formal spec.... I just find it a convenient place to keep all our queries so we don't have to write them anew, and so we can note who's implementing what and what queries have been implemented already. I've also been editing it so we know what "type" the queries are, so when the TA asks for, as example, an aggregation query, we know which button to click. That being said I think the spec just affects Brian and I mostly, since most of these changes just reflect the flight queries

**Comment by AaronCui** [comment]
Offline discussion result: 

The issues I raised did not come from this PR. Our original design was ambiguous for airplane_4. It is suppose to be a 1 to many relationship (1 airplane used by multiple flights), but for some reason we track flight data from airplane. This PR solves the issue of it being forced as 1 to 1, will merge as is but might add new PR to change the original design.

**Review by AaronCui — APPROVED** [review]

**Pull request merged**
